ALTER TABLE customer ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS current_time_zone TEXT;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS account_id TEXT;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS account_id_encrypt TEXT;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS ali_id TEXT;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS ali_id_encrypt TEXT;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS login_id_encrypt TEXT;
